### PR TITLE
Update configuration with partial code refactoring.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from groupdocs-total/GroupDocs.Total-for-NET-MVC#94 with partial code style refactoring using StyleCop.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/pullRequest?prid=5681702&bid=18598356)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Annotation-for-.NET-WebForms/pullRequest?prid=5681703&bid=18598357)

**Review by Pavel-Teplitsky — APPROVED** [review]

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Annotation-for-.NET-WebForms/pullRequest?prid=5681703&bid=18598357)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/pullRequest?prid=5681702&bid=18598356)

**Pull request merged**
